### ISSUE TITLE
android 12 以上设备闪退，请修改Notification flag

### ISSUE THREAD

**Issue by Alexxiaopang** [iDeMonnnnnn/Homer#2]
在安卓12的设备上运行，由于启动service服务之后无法执行startForeground，createNotificationByChannel里面的PendingIntent.getActivity方法使用错flag了，导致过20多秒后闪退
安卓12的PendingIntent  flag已经修改，请修改对应Flag
//android 源码如下:
   public static PendingIntent getActivity(Context context, int requestCode,
            Intent intent, @Flags int flags) {
        return getActivity(context, requestCode, intent, flags, null);
    }

建议做以下修改
    fun getPushIntentFlag(): Int {
        return if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            PendingIntent.FLAG_IMMUTABLE
        } else {
            PendingIntent.FLAG_UPDATE_CURRENT
        }
    }
替换项目中的  PendingIntent.FLAG_UPDATE_CURRENT

打扰了

**Comment by iDeMonnnnnn** [comment]
已改，thx
